// HEADERNAVFOOTER
export const SET_HEADER_LINKS = 'SET_HEADER_LINKS';
export const SET_NAVBAR_LINKS = 'SET_NAVBAR_LINKS';
export const CHANGE_NAVBAR_ACTIVE = 'CHANGE_NAVBAR_ACTIVE';

// USER
export const SET_USER_ORDERS = 'SET_USER_ORDERS';
export const SET_ORDER_DETAIL = 'SET_ORDER_DETAIL';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';

// USER E-BAG
export const SET_BAGGED_FOODS = 'SET_BAGGED_FOODS';
export const ADD_BAGGED_FOOD = 'ADD_BAGGED_FOOD';

// E-RESTAURANT
export const SET_FOOD_CATEGORIES='SET_FOOD_CATEGORIES';
export const SET_FOODS='SET_FOODS';
export const FILTER_FOOD_WITH_CATEGORY_ID='FILTER_FOOD_WITH_CATEGORY_ID';
export const FILTER_FOOD_WITH_QUERY = 'FILTER_FOOD_WITH_QUERY';